import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';

import '../globals.css';
import { Header, Footer } from '@/components/index';

export const metadata: Metadata = {
  title: 'E-commerce Furniro',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Header />
      <main>{children}</main>
      <Footer />
    </ClerkProvider>
  );
}
