import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins, Montserrat } from 'next/font/google';

import "./globals.css";
import {Header, Footer} from "@/components/index";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins"
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["700"],
  variable: "--font-montserrat"
})


export const metadata: Metadata = {
  title: "Create E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${montserrat.variable} ${poppins.variable}`}>
        <body>
          <Header />
          <main>{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
